# Generated by Django 3.1.5 on 2021-01-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210126_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
