# Generated by Django 3.1.5 on 2021-01-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
